all:
	g++ test_ppForm_cubic_function.cpp -o runge_ppForm -O2
	g++ test_BSpline_cubic_function.cpp -o runge_BSpline -O2
	g++ test_random_curve.cpp -o curve -O2
	g++ test_curve_helix.cpp -o helix -O2
	g++ test_curve_cardioid.cpp -o cardioid -O2
	g++ assignmentA.cpp -o A -O2
	g++ assignmentC.cpp -o C -O2
	g++ assignmentD.cpp -o D -O2
	g++ assignmentE.cpp -o E -O2

clean:
	rm runge_ppForm runge_BSpline curve helix cardioid A C D E